"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { apiOrigin, downloadFile, getAccessToken } from "@/lib/api-client";
import { useSession } from "@/components/session";
import { CopyLink } from "@/components/copy-link";
import { Button } from "@/components/ui";

/**
 * The card is shown at close to the size it prints, because the decision an
 * owner is making here is a physical one — will this scan from across a
 * table, is the name legible on a table tent.
 */
export default function QrPage() {
  const { current } = useSession();
  const [busy, setBusy] = useState<string | null>(null);

  if (!current) return null;

  const menuUrl = `${typeof window !== "undefined" ? window.location.origin : ""}/m/${current.publicCode}`;

  async function download(format: "png" | "pdf" | "svg") {
    if (!current) return;
    setBusy(format);
    try {
      await downloadFile(
        `/businesses/${current.id}/qr?format=${format}`,
        `${slug(current.name)}-menu-qr.${format}`,
      );
    } finally {
      setBusy(null);
    }
  }

  return (
    <div className="mx-auto max-w-3xl px-5 py-8 sm:px-6 sm:py-10 lg:px-10 lg:py-12">
      <header className="mb-8">
        <h1 className="text-[26px] font-semibold leading-tight tracking-tight sm:text-[30px]">QR code</h1>
        <p className="mt-1 text-[14.5px] text-muted">
          Print it for tables, counters, or the window. It never expires.
        </p>
      </header>

      <div className="grid gap-8 sm:grid-cols-[240px_1fr]">
        <QrPreview businessId={current.id} />

        <div>
          <h2 className="font-display text-[16px] font-semibold">Download</h2>
          <p className="mt-1 text-[13.5px] leading-relaxed text-muted">
            PNG for anything you print yourself. PDF keeps the artwork sharp at any
            size — send that one to a print shop.
          </p>

          <div className="mt-4 flex flex-wrap gap-2">
            <Button variant="primary" loading={busy === "png"} onClick={() => void download("png")}>
              PNG, print quality
            </Button>
            <Button loading={busy === "pdf"} onClick={() => void download("pdf")}>
              PDF, vector
            </Button>
            <Button loading={busy === "svg"} onClick={() => void download("svg")}>
              SVG
            </Button>
          </div>

          <div className="mt-8 border-t border-line pt-6">
            <h2 className="font-display text-[16px] font-semibold">The link behind it</h2>
            <p className="mt-1 text-[13.5px] text-muted">
              The code points here. Renaming your business won't break printed cards.
            </p>
            <div className="mt-3">
              <CopyLink url={menuUrl} />
            </div>
          </div>

          <div className="mt-8 rounded-2xl border border-line bg-surface p-4">
            <h3 className="text-[14px] font-medium">Want them printed?</h3>
            <p className="mt-1 text-[13.5px] leading-relaxed text-muted">
              We print PVC cards, epoxy tags and acrylic stands, and post them to you.
              Each table gets its own code.
            </p>
            <Link href="/merch" className="mt-3 inline-block">
              <Button size="sm">See printed cards</Button>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}

/**
 * The card is fetched rather than pointed at with an <img src>: the endpoint
 * needs a bearer token, and an image request cannot carry one. The SVG is
 * inlined so it stays crisp at any zoom.
 */
function QrPreview({ businessId }: { businessId: string }) {
  const [svg, setSvg] = useState<string | null>(null);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    let cancelled = false;
    void (async () => {
      try {
        const res = await fetch(
          `${apiOrigin()}/businesses/${businessId}/qr?format=svg`,
          {
            headers: { Authorization: `Bearer ${getAccessToken() ?? ""}` },
            credentials: "include",
          },
        );
        if (!res.ok) throw new Error("preview failed");
        const text = await res.text();
        if (!cancelled) setSvg(text);
      } catch {
        if (!cancelled) setFailed(true);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [businessId]);

  return (
    <div className="overflow-hidden rounded-2xl border border-line bg-surface p-4 shadow-card">
      {failed ? (
        <p className="py-16 text-center text-[13px] text-faint">
          Preview unavailable. The downloads still work.
        </p>
      ) : svg ? (
        <div
          className="[&>svg]:h-auto [&>svg]:w-full"
          // The SVG is generated by our own API from the owner's business
          // name, which is escaped during composition.
          dangerouslySetInnerHTML={{ __html: svg }}
        />
      ) : (
        <div className="aspect-[105/148] w-full animate-pulse rounded-xl bg-raised" />
      )}
    </div>
  );
}

function slug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "menu";
}
