/**
 * Brand pieces shared by the receipt and the bill.
 *
 * Both documents carry the same mark and the same credit line, and they are
 * generated by different files, so the drawing lives here rather than being
 * copied into each and drifting.
 */

/**
 * The mark, in pdfkit primitives.
 *
 * Not an embedded raster: a receipt is often printed on a thermal printer
 * where a small PNG turns to mush, and these shapes are simple enough that
 * drawing them keeps the edges crisp at any resolution.
 */
export function drawMark(
  doc: PDFKit.PDFDocument,
  x: number,
  y: number,
  size: number,
  opacity = 0.55,
): void {
  const u = size / 32;

  doc.save();
  doc.fillColor("#1C1C1E").opacity(opacity);
  doc.roundedRect(x, y, size, size, 8 * u).fill();

  doc.fillColor("#FFFFFF").opacity(1);
  doc
    .lineWidth(2.5 * u)
    .strokeColor("#FFFFFF")
    .roundedRect(x + 6.25 * u, y + 6.25 * u, 12.5 * u, 12.5 * u, 3.75 * u)
    .stroke();
  doc.roundedRect(x + 10.5 * u, y + 10.5 * u, 4 * u, 4 * u, 1.25 * u).fill();
  doc.roundedRect(x + 20.5 * u, y + 20.5 * u, 6 * u, 6 * u, 2 * u).fill();
  doc.restore();
}

/** Mark and wordmark, centred as one group within `width` starting at `left`. */
export function drawCredit(
  doc: PDFKit.PDFDocument,
  left: number,
  width: number,
  y: number,
  fontSize = 6,
): void {
  const markSize = fontSize * 0.85;
  const label = "menu.irad.solutions";

  doc.font("Helvetica").fontSize(fontSize);
  const labelWidth = doc.widthOfString(label);
  const groupLeft = left + (width - (markSize + 2 + labelWidth)) / 2;

  drawMark(doc, groupLeft, y, markSize);
  doc.save();
  doc.fillColor("#1C1C1E").opacity(0.55);
  doc.text(label, groupLeft + markSize + 2, y + 0.4, { lineBreak: false });
  doc.restore();
  doc.opacity(1).fillColor("#000000");
}

/**
 * The owner's logo, if there is one, fitted into a square.
 *
 * Returns whether anything was drawn, so callers can lay out around it. Never
 * throws: a corrupt or missing logo must not stop someone printing a bill.
 * Logos are stored as PNG precisely so this can work — pdfkit cannot embed
 * WebP.
 */
export function drawLogo(
  doc: PDFKit.PDFDocument,
  logo: Buffer | null,
  x: number,
  y: number,
  size: number,
): boolean {
  if (!logo) return false;
  try {
    doc.image(logo, x, y, { fit: [size, size], align: "center", valign: "center" });
    return true;
  } catch {
    return false;
  }
}

/** ₹ for rupees; other currencies fall back to the bare amount. */
export function money(amount: string, currency: string): string {
  return `${currency === "INR" ? "₹" : ""}${amount}`;
}
